apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: demkonst/blogapp-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
manifests:
  rawYaml:
    - ./infra/k8s/*
